//! Language packs → Slint's bundled translations and the Rust pack list.
//!
//! The only sources are `translations/languages.json` (the language list) and one
//! `translations/<code>.json` pack per listed language, keyed by the English message (see
//! docs/development/translations.md). From them this writes, under `OUT_DIR`:
//!
//! - `translations/<code>/LC_MESSAGES/falcon-native.po`, which the `slint!` macro bundles when
//!   `SLINT_BUNDLE_TRANSLATIONS` points at the folder. Nothing generated is committed, so a pack can
//!   never disagree with its `.po`.
//! - `packs.rs`, the list `i18n.rs` includes: each language's code, own name, locale matches, plural
//!   rule and embedded pack text.
//!
//! Every non-release build also bundles the pseudo-language `xx-TEST` from
//! `translations/test/xx-TEST.json`, so tests can drive both the Slint and the Rust path.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

#[path = "src/i18n_rules.rs"]
#[allow(dead_code)]
mod i18n_rules;

/// Slint looks each `@tr` up under this context; every marked message names it explicitly so one
/// English text has one translation wherever it appears.
const CONTEXT: &str = "falcon";

struct Lang {
    code: String,
    name: String,
    matches: Vec<String>,
    plural: String,
    pack_path: PathBuf,
}

pub fn build() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let dir = manifest.join("translations");
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let profile = std::env::var("PROFILE").unwrap_or_default();
    println!("cargo:rerun-if-changed=translations");
    println!("cargo::rustc-check-cfg=cfg(falcon_pseudo_language)");

    let mut langs = read_language_list(&dir.join("languages.json"));
    for l in &langs {
        assert!(l.pack_path.is_file(), "translations/languages.json lists {} but translations/{}.json is missing", l.code, l.code);
    }
    let pseudo = i18n_rules::include_pseudo_language(&profile);
    if pseudo {
        langs.push(Lang {
            code: i18n_rules::PSEUDO_CODE.into(),
            name: i18n_rules::PSEUDO_CODE.into(),
            matches: Vec::new(),
            plural: i18n_rules::PSEUDO_RULE.into(),
            pack_path: dir.join("test").join(format!("{}.json", i18n_rules::PSEUDO_CODE)),
        });
        println!("cargo:rustc-cfg=falcon_pseudo_language");
    }

    let po_root = out.join("translations");
    let _ = std::fs::remove_dir_all(&po_root); // a language dropped from the list must not linger
    let mut hash = Fnv::new();
    let mut packs_rs = String::from("// @generated by build_translations.rs from translations/languages.json.\n");
    let mut listed = String::new();
    for l in &langs {
        let text = std::fs::read_to_string(&l.pack_path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", l.pack_path.display()));
        hash.add(l.code.as_bytes());
        hash.add(text.as_bytes());
        let rule = i18n_rules::plural_rule(&l.plural).expect("checked when the list was read");
        let entries = read_pack(&l.pack_path, &text, rule);
        let po_dir = po_root.join(&l.code).join("LC_MESSAGES");
        std::fs::create_dir_all(&po_dir).expect("create the .po folder");
        std::fs::write(po_dir.join("falcon-native.po"), po_file(&l.code, rule, &entries)).expect("write the .po");
        let pack_path = l.pack_path.to_str().expect("pack path is UTF-8");
        if l.code == i18n_rules::PSEUDO_CODE {
            writeln!(packs_rs, "#[cfg(test)]\npub(crate) static PSEUDO_PACK: &str = include_str!({pack_path:?});").unwrap();
        } else {
            writeln!(
                listed,
                "    Language {{ code: {:?}, name: {:?}, matches: &{:?}, plural: {:?}, pack: include_str!({pack_path:?}) }},",
                l.code, l.name, l.matches, l.plural
            )
            .unwrap();
        }
    }
    writeln!(packs_rs, "pub(crate) static LANGUAGES: &[Language] = &[\n{listed}];").unwrap();
    std::fs::write(out.join("packs.rs"), packs_rs).expect("write packs.rs");

    // Slint fails the build on a bundle folder with no catalogue, so a release with no packs
    // simply builds without bundling; English needs none.
    if !langs.is_empty() {
        println!("cargo:rustc-env=SLINT_BUNDLE_TRANSLATIONS={}", po_root.display());
    }
    // The macro does not track the `.po` files; a changed hash makes Cargo recompile the crate.
    println!("cargo:rustc-env=FALCON_TRANSLATIONS_HASH={:016x}", hash.0);
}

fn read_language_list(path: &Path) -> Vec<Lang> {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let doc: serde_json::Value =
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("{} is not valid JSON: {e}", path.display()));
    let entries = doc.get("languages").and_then(|v| v.as_array()).expect("languages.json: \"languages\" must be a list");
    let dir = path.parent().expect("translations folder");
    let mut seen = Vec::new();
    entries
        .iter()
        .map(|e| {
            let field = |k: &str| {
                e.get(k).and_then(|v| v.as_str()).unwrap_or_else(|| panic!("languages.json: an entry lacks the text field \"{k}\""))
            };
            let code = field("code").to_string();
            assert!(
                !code.is_empty() && code.chars().all(|c| c.is_ascii_alphanumeric() || c == '-'),
                "languages.json: code {code:?} must be letters, digits and hyphens"
            );
            assert!(!code.eq_ignore_ascii_case("en"), "languages.json: English is the source language and has no pack");
            assert!(code != i18n_rules::PSEUDO_CODE, "languages.json: {code} is reserved for tests");
            assert!(!seen.contains(&code.to_ascii_lowercase()), "languages.json: {code} is listed twice");
            seen.push(code.to_ascii_lowercase());
            let plural = field("plural").to_string();
            assert!(i18n_rules::plural_rule(&plural).is_some(), "languages.json: {code} names an unknown plural rule {plural:?}");
            let matches = e
                .get("match")
                .and_then(|v| v.as_array())
                .unwrap_or_else(|| panic!("languages.json: {code} needs a \"match\" list"))
                .iter()
                .map(|m| m.as_str().unwrap_or_else(|| panic!("languages.json: {code}'s match list holds text only")).to_string())
                .collect();
            Lang { pack_path: dir.join(format!("{code}.json")), name: field("name").to_string(), code, matches, plural }
        })
        .collect()
}

enum Value {
    Text(String),
    Forms(Vec<String>),
}

/// The pack's entries in file order. A counted message's value lists exactly the rule's categories.
fn read_pack(path: &Path, text: &str, rule: &i18n_rules::PluralRuleDef) -> Vec<(String, Value)> {
    let doc: serde_json::Map<String, serde_json::Value> =
        serde_json::from_str(text).unwrap_or_else(|e| panic!("{} is not a JSON object of messages: {e}", path.display()));
    doc.into_iter()
        .map(|(key, v)| {
            let value = match v {
                serde_json::Value::String(s) => Value::Text(s),
                serde_json::Value::Object(forms) => {
                    let mut names: Vec<&str> = forms.keys().map(String::as_str).collect();
                    names.sort_unstable();
                    let mut want = rule.categories.to_vec();
                    want.sort_unstable();
                    assert!(
                        names == want,
                        "{}: {key:?} must have exactly the plural forms {:?}",
                        path.display(),
                        rule.categories
                    );
                    Value::Forms(
                        rule.categories
                            .iter()
                            .map(|c| forms[*c].as_str().unwrap_or_else(|| panic!("{}: {key:?}: forms are text", path.display())).to_string())
                            .collect(),
                    )
                }
                _ => panic!("{}: {key:?} must be text or an object of plural forms", path.display()),
            };
            (key, value)
        })
        .collect()
}

fn po_file(code: &str, rule: &i18n_rules::PluralRuleDef, entries: &[(String, Value)]) -> String {
    let mut po = String::new();
    writeln!(po, "msgid \"\"\nmsgstr \"\"").unwrap();
    writeln!(po, "\"Content-Type: text/plain; charset=UTF-8\\n\"").unwrap();
    writeln!(po, "\"Language: {code}\\n\"").unwrap();
    writeln!(po, "\"Plural-Forms: {}\\n\"\n", rule.po_header).unwrap();
    for (key, value) in entries {
        writeln!(po, "msgctxt {}", po_quote(CONTEXT)).unwrap();
        writeln!(po, "msgid {}", po_quote(key)).unwrap();
        match value {
            Value::Text(s) => writeln!(po, "msgstr {}\n", po_quote(s)).unwrap(),
            Value::Forms(forms) => {
                // Slint finds a plural message by its singular msgid; the English plural is not
                // needed for the lookup, so the key stands in for it.
                writeln!(po, "msgid_plural {}", po_quote(key)).unwrap();
                for (i, f) in forms.iter().enumerate() {
                    writeln!(po, "msgstr[{i}] {}", po_quote(f)).unwrap();
                }
                po.push('\n');
            }
        }
    }
    po
}

fn po_quote(s: &str) -> String {
    let mut q = String::with_capacity(s.len() + 2);
    q.push('"');
    for c in s.chars() {
        match c {
            '\\' => q.push_str("\\\\"),
            '"' => q.push_str("\\\""),
            '\n' => q.push_str("\\n"),
            '\t' => q.push_str("\\t"),
            '\r' => q.push_str("\\r"),
            _ => q.push(c),
        }
    }
    q.push('"');
    q
}

/// FNV-1a, enough to notice that a pack changed.
struct Fnv(u64);
impl Fnv {
    fn new() -> Self {
        Fnv(0xcbf2_9ce4_8422_2325)
    }
    fn add(&mut self, bytes: &[u8]) {
        for b in bytes.iter().chain([0xffu8].iter()) {
            self.0 ^= u64::from(*b);
            self.0 = self.0.wrapping_mul(0x0100_0000_01b3);
        }
    }
}
