# Dependency distribution choices. Falcon itself is Apache-2.0; upstream licences are retained.
accepted = ["MIT", "Apache-2.0", "BSD-3-Clause", "BSD-2-Clause", "ISC", "Zlib", "Unicode-3.0", "BSL-1.0", "CC0-1.0", "OFL-1.1", "IJG", "LGPL-2.1", "LicenseRef-Slint-Royalty-free-2.0"]
targets = ["x86_64-pc-windows-msvc", "aarch64-apple-darwin"]
ignore-dev-dependencies = true
ignore-build-dependencies = false

[i-slint-backend-selector.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-backend-selector.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
license = "LicenseRef-Slint-Royalty-free-2.0"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-backend-winit.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-backend-winit.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
license = "LicenseRef-Slint-Royalty-free-2.0"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-common.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-common.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
license = "LicenseRef-Slint-Royalty-free-2.0"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-compiler.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-compiler.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
license = "LicenseRef-Slint-Royalty-free-2.0"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-core.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-core.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
license = "LicenseRef-Slint-Royalty-free-2.0"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-core-macros.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-core-macros.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
license = "LicenseRef-Slint-Royalty-free-2.0"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-renderer-femtovg.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-renderer-femtovg.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
license = "LicenseRef-Slint-Royalty-free-2.0"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[slint.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[slint.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
license = "LicenseRef-Slint-Royalty-free-2.0"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[slint-macros.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[slint-macros.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
license = "LicenseRef-Slint-Royalty-free-2.0"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[brotli-decompressor.clarify]
license = "BSD-3-Clause"
[[brotli-decompressor.clarify.files]]
path = "LICENSE"
license = "BSD-3-Clause"
checksum = "c0c56f26d9c051cac4d200c34c84e7ae9aaa853e01a982a1df08b09931e518ae"

[windows.clarify]
license = "MIT"
[[windows.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-collections.clarify]
license = "MIT"
[[windows-collections.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-core.clarify]
license = "MIT"
[[windows-core.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-future.clarify]
license = "MIT"
[[windows-future.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-implement.clarify]
license = "MIT"
[[windows-implement.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-interface.clarify]
license = "MIT"
[[windows-interface.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-link.clarify]
license = "MIT"
[[windows-link.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-numerics.clarify]
license = "MIT"
[[windows-numerics.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-result.clarify]
license = "MIT"
[[windows-result.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-strings.clarify]
license = "MIT"
[[windows-strings.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-sys.clarify]
license = "MIT"
[[windows-sys.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-targets.clarify]
license = "MIT"
[[windows-targets.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-threading.clarify]
license = "MIT"
[[windows-threading.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows_x86_64_msvc.clarify]
license = "MIT"
[[windows_x86_64_msvc.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"
